# @name route-get-tasks

GET http://localhost:3333/tasks

###

# @name route-post-task

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Task One",
  "description": "Test Task",
  "created_at": "2023-09-20T12:00:00Z",
  "completed_at": null,
  "updated_at": "2023-09-20T12:00:00Z"
}

###

# @name route-delete-task

DELETE http://localhost:3333/tasks/b0af79c4-d2bb-4772-bec8-b776353