# @name route-get-tasks

GET http://localhost:3333/tasks

###

# @name route-post-task

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Study Modus Operandis",
  "description": "Estudar node"
}

###

# @name route-delete-task

DELETE http://localhost:3333/tasks/ca49c454-7814-4d2d-bf09-00d5e0464acd


###

# @name route-get-tasks-with-search

GET http://localhost:3333/tasks?search=task

###

# @name route-update-task

PUT http://localhost:3333/tasks/39780c9d-ff88-46ee-a524-b4ff67e8ff53
Content-Type: application/json

{
  "title": "Change Modus Operandis",
  "description": "Estudar node 2"
}
