# @name route-get-tasks

GET http://localhost:3333/tasks

###

# @name route-post-task

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Study Modus Operandis",
  "description": "Estudar node"
}

###

# @name route-delete-task

DELETE http://localhost:3333/tasks/b0af79c4-d2bb-4772-bec8-b776353


###

# @name route-get-tasks-with-search

GET http://localhost:3333/tasks?search=task